### ISSUE TITLE
Add semcov for grpc request and response sizes

### ISSUE THREAD

**Issue by anuragagarwal561994** [open-telemetry/semantic-conventions-java#28] opened 2023-10-23 18:19 UTC
We are trying to add functionality to yield grpc request and response size metrics.

As I can see it is not part of semcov, how can it be added so we can change the opentelemetry-java instrumentation to yield these metrics?

**Comment by breedx-splk** [comment] 2023-10-24 23:15
I think this would fall under this: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-metrics.md#metric-rpcserverrequestsize

**Comment by anuragagarwal561994** [comment] 2023-10-25 12:06
Yes this is only the metric we wanted to add as attribute so we can extract that attribute in this metric.

**Comment by breedx-splk** [comment] 2023-10-25 20:31
Gotcha. I don't think this repo yet has any support for autogenerating the metric conventions from the yaml, so this definitely relates to #12.

**Comment by jack-berg** [comment] 2024-08-19 22:14
Closing as duplicate of #12. Keeping #12 instead of this because its more generic, and came first.

**Closed by jack-berg** 2024-08-19 22:14 UTC
